### PR TITLE
python3.10 added

### PR DESCRIPTION
**Pull request by mhkarimi1383**
Adding python3.10
also I want to add 3.11

### CODE REVIEW

**Comment by mhkarimi1383** [comment]
python:3.10-slim is getting following error
```
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py): started
  Building wheel for httptools (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/httptools
      copying httptools/__init__.py -> build/lib.linux-x86_64-cpython-310/httptools
      copying httptools/_version.py -> build/lib.linux-x86_64-cpython-310/httptools
      creating build/lib.linux-x86_64-cpython-310/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.linux-x86_64-cpython-310/httptools/parser
      copying httptools/parser/errors.py -> build/lib.linux-x86_64-cpython-310/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.linux-x86_64-cpython-310/httptools/parser
      copying httptools/parser/url_parser.c -> build/lib.linux-x86_64-cpython-310/httptools/parser
      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/httptools
      creating build/temp.linux-x86_64-cpython-310/httptools/parser
      creating build/temp.linux-x86_64-cpython-310/vendor
      creating build/temp.linux-x86_64-cpython-310/vendor/llhttp
      creating build/temp.linux-x86_64-cpython-310/vendor/llhttp/src
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-install-2p1u2yc3/httptools_04dedf8928a44a59a473c6b5219d4bb7/vendor/llhttp/include -I/tmp/pip-install-2p1u2yc3/httptools_04dedf8928a44a59a473c6b5219d4bb7/vendor/llhttp/src -I/usr/local/include/python3.10 -c httptools/parser/parser.c -o build/temp.linux-x86_64-cpython-310/httptools/parser/parser.o -O2
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools, websockets, uvloop, sniffio, PyYAML, python-dotenv, idna, h11, gunicorn, click, asgiref, uvicorn, anyio, watchgod
  Running setup.py install for httptools: started
  Running setup.py install for httptools: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for httptools did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      running install
      /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/httptools
      copying httptools/__init__.py -> build/lib.linux-x86_64-cpython-310/httptools
      copying httptools/_version.py -> build/lib.linux-x86_64-cpython-310/httptools
      creating build/lib.linux-x86_64-cpython-310/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.linux-x86_64-cpython-310/httptools/parser
      copying httptools/parser/errors.py -> build/lib.linux-x86_64-cpython-310/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.linux-x86_64-cpython-310/httptools/parser
      copying httptools/parser/url_parser.c -> build/lib.linux-x86_64-cpython-310/httptools/parser
      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/httptools
      creating build/temp.linux-x86_64-cpython-310/httptools/parser
      creating build/temp.linux-x86_64-cpython-310/vendor
      creating build/temp.linux-x86_64-cpython-310/vendor/llhttp
      creating build/temp.linux-x86_64-cpython-310/vendor/llhttp/src
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-install-2p1u2yc3/httptools_04dedf8928a44a59a473c6b5219d4bb7/vendor/llhttp/include -I/tmp/pip-install-2p1u2yc3/httptools_04dedf8928a44a59a473c6b5219d4bb7/vendor/llhttp/src -I/usr/local/include/python3.10 -c httptools/parser/parser.c -o build/temp.linux-x86_64-cpython-310/httptools/parser/parser.o -O2
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> httptools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip
The command '/bin/sh -c pip install --no-cache-dir -r /tmp/requirements.txt' returned a non-zero code: 1
```

**Comment by mhkarimi1383** [comment]
I think I have to install build-essential

**Comment by mhkarimi1383** [comment]
why PYTHON_VERSION env is wrong?

**Comment by mhkarimi1383** [comment]
@tiangolo 
Any updates?

**Comment by tiangolo** [comment]
Thanks for the interest! This was handled here: https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/99 :tada: 

Given that, I'll close this one, but thanks for the effort! :rocket:

**Pull request closed without merging**
