### PR TITLE
Create python3.8-alpine3.12.dockerfile

### PR DESCRIPTION
**Pull request by hopeswiller**
Installing cryptography in alpine 3.10 fails. It needs at least Alpine 3.12 to be able to match the rust extension requirement >=1.41.0

### CODE REVIEW

**Comment by wallyhall** [comment]
We've just hit this issue too.  It'd be very helpful to have this merged and filtered down into the FastAPI image too...  Am very happy to perform some testing etc if that helps.

**Comment by wallyhall** [comment]
For those not familiar with the backstory to this, there is some [detail on Cryptography installation under Alpine since version 3.5 published online](https://cryptography.io/en/latest/installation/#alpine).

Quoting from that:

`Warning

The Rust available by default in Alpine < 3.12 is older than the minimum supported version. See the Rust installation instructions for information about installing a newer Rust.`

Unfortunately the pre-built Cryptography wheels aren't (currently) available for Alpine either:

`Some Linux distributions (most notably Alpine) are not manylinux compatible so we cannot distribute wheels for them.`

**Comment by tiangolo** [comment]
Hey! Thanks for the interest. There's now a version with Python 3.9 and Alpine 3.14. Does that work for you?

I would rather not add more Alpine versions per Python version.

**Comment by wallyhall** [comment]
@tiangolo - thank-you so much, this is really appreciated.  I'll give it a go right now, and try to confirm by the end of today (I'm on holiday next week).

**Comment by wallyhall** [comment]
> @tiangolo - thank-you so much, this is really appreciated. I'll give it a go right now, and try to confirm by the end of today (I'm on holiday next week).

Looks to be working a champ.  Thank-you again!

**Comment by tiangolo** [comment]
Thanks for reporting back @wallyhall! :rocket:

**Pull request closed without merging**
