### PR TITLE
✨ Add support for Python 3.12

### PR DESCRIPTION
**Pull request by shepilov-vladislav**

### CODE REVIEW

**Comment by shepilov-vladislav** [comment]
@tiangolo can it be merged?

**Comment by shepilov-vladislav** [comment]
@tiangolo Maybe you should give maintainer rights additionally to some other active user of the community? Python 3.12 is released in October 2023 and moreover, your framework supports it. I suspect you have a lot of work to do and don't have time to review all the pull requests. But we depend on your code, and we maintain our codebase on the current version of Python. And there is only one way out in this situation - to keep additional versions of docker images in your docker registry until you merge them.

**Comment by eliasdjup** [comment]
+1

**Comment by theobouwman** [comment]
+1

**Comment by mhkarimi1383** [comment]
+1

**Comment by mhkarimi1383** [comment]
@tiangolo We could switch to a templating structure and getting last N versions of python, so no need to have update like this anymore :)

**Comment by tiangolo** [comment]
Thanks for the interest! :cake: 

Now that Uvicorn supports managing workers with `--workers`, including restarting dead ones, there's no need for Gunicorn. That also means that it's much simpler to build a Docker image from scratch now, I updated the docs to explain it.

Because of that, I deprecated this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image

Given that, I'll now close this one, but thanks for the effort! :coffee:

**Pull request closed without merging**
